#
dist: trusty
sudo: false
addons:
  postgresql: '9.4'
  chrome: stable
language: ruby
cache: bundler
rvm:
  - 2.4
  - 2.5.0
env:
  - RAILS_GEM="~> 5.0.0" PG_GEM="~> 0.18"
  - RAILS_GEM="~> 5.1.0"
  - RAILS_GEM=">= 5.2.0.rc2,< 5.3.0"
before_install:
  - gem install bundler -v 1.14.6
