# under combustion for some reason not happy with the 'default' YML thing.
# default: &default
#   adapter: postgresql
#   encoding: unicode



test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RAILS_PG_DB'] || "attr_json_project_test" %>

# Warning, combustion will drop your dev database too....
development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RAILS_PG_DB'] || "attr_json_project_dev_throwaway" %>
